name: ptwcode_lints
description: This package contains a set of lints for Flutter to encourage good coding practices.
version: 1.0.25
repository: https://github.com/alidev0/ptwcode_lints

environment:
  sdk: ^3.6.2

dependencies:
  analyzer: ^8.0.0
  analyzer_plugin: ^0.13.0
  custom_lint_builder: ^0.8.1

dev_dependencies:
  flutter_lints: ^6.0.0
